name = "siren-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [

  { pattern = "anang.celengstore.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "df.game.naver.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "instagram.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "creativeservices.netflix.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "support.zoom.us.anang.celengstore.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "graph.facebook.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "facebook.com.anang.celengstore.my.id", custom_domain = true },
  { pattern = "engineering.instagram.com.anang.celengstore.my.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "cd368af4c5d34c20a800a4d628352c7a"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/Anang110400/SirenWeb/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/Anang110400/SirenWeb/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/Anang110400/SirenWeb/refs/heads/master/web/link.html"
